#!/usr/bin/env python
# Copyright (C) 2019 Adrian Carpenter
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os
import datetime

def run(command) :
	stream = os.popen(command)

	return stream.read()

dateString = datetime.datetime.now().strftime("%B %Y")

output = run('git log -1 --format=%cd --date=format:"%y %m"').split()

commitYear = output[0]
commitMonth = str(int(output[1]))
commitCount = run('git rev-list --count HEAD --since="1 '+dateString+'"').strip()
commitBranch = run('git rev-parse --abbrev-ref HEAD').strip()

versionString = commitYear+"."+commitMonth+"."+commitCount+"-"+commitBranch

versionHeaderFile = open("src/includes/PingnooVersion.h", "w")

versionHeaderFile.write('#if !defined(PINGNOO_VERSION_H)\n')
versionHeaderFile.write('#define PINGNOO_VERSION_H\n')
versionHeaderFile.write('#define PINGNOO_VERSION "'+commitYear+'.'+commitMonth+'.'+commitCount+'-'+commitBranch+'"\n')
versionHeaderFile.write('#endif\n')

versionHeaderFile.close()
