#ifndef NEDRYSOFT_RIBBON_RIBBONSPEC_H
#define NEDRYSOFT_RIBBON_RIBBONSPEC_H

#if defined(RIBBON_DESIGNER_EXPORT)
#include <QtUiPlugin/QDesignerExportWidget>
#define RIBBON_WIDGET_EXPORT Q_DECL_EXPORT
#else
#if defined(NEDRYSOFT_LIBRARY_RIBBON_EXPORT)
#define RIBBON_WIDGET_EXPORT Q_DECL_EXPORT
#else
#define RIBBON_WIDGET_EXPORT Q_DECL_IMPORT
#endif
#endif

#endif // NEDRYSOFT_RIBBON_RIBBONSPEC_H
