#ifndef FIZZYADE_RIBBON_RIBBONSPEC_H
#define FIZZYADE_RIBBON_RIBBONSPEC_H

#if defined(RIBBON_DESIGNER_EXPORT)
#include <QtUiPlugin/QDesignerExportWidget>
#define RIBBON_WIDGET_EXPORT Q_DECL_EXPORT
#else
#if defined(FIZZYADE_LIBRARY_RIBBON_EXPORT)
#define RIBBON_WIDGET_EXPORT Q_DECL_EXPORT
#else
#define RIBBON_WIDGET_EXPORT Q_DECL_IMPORT
#endif
#endif

#endif // FIZZYADE_RIBBON_RIBBONSPEC_H
